-- Cold-start proposals (roadmap slice S-02) — the repo's first migration.
--
-- Two tables, deliberately split so a forced purge of provider-derived data leaves
-- the user's own event history intact (PRD §Guardrails):
--   recipes   — provider-derived reference, exactly the three fields Spoonacular's
--               terms permit storing indefinitely (id, title, image). Storing any
--               other provider field — summary, cuisines, dishTypes, ingredients,
--               instructions, nutrition — is prohibited by FR-011, including in
--               derived or transformed form.
--   proposals — app-owned event record: who was shown what, when, and which cuisine
--               *the app pinned in its request*. Never the response's cuisines[],
--               which is a provider field and often empty anyway.

create table if not exists public.recipes (
  spoonacular_id bigint primary key,
  title text not null,
  image text,
  created_at timestamptz not null default now()
);

create table if not exists public.proposals (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  spoonacular_id bigint not null references public.recipes (spoonacular_id),
  -- The cuisine the app asked for, not the one the provider classified back.
  requested_cuisine text not null,
  -- Reserved for S-05 (meal type); always null in the cold-start slice.
  requested_type text,
  proposed_at timestamptz not null default now()
);

-- Access path for S-03's rating history and S-05's "not seen in >= 2 weeks" rule.
create index if not exists proposals_user_id_proposed_at_idx
  on public.proposals (user_id, proposed_at desc);

-- RLS: the database is the access-control boundary, because the endpoint writes with
-- the anon key on the user's own cookie session (no service-role client in this slice).

alter table public.recipes enable row level security;
alter table public.proposals enable row level security;

-- recipes is a shared catalogue with no user data; restricting it would break the
-- upsert without protecting anything. See context/foundation/lessons.md — revisit
-- before S-03 starts rendering these rows back to other users.
grant select, insert on public.recipes to authenticated;

create policy "recipes are readable by any authenticated user"
  on public.recipes for select to authenticated
  using (true);

create policy "recipes are insertable by any authenticated user"
  on public.recipes for insert to authenticated
  with check (true);

grant select, insert on public.proposals to authenticated;
grant usage, select on sequence public.proposals_id_seq to authenticated;

-- (select auth.uid()) rather than bare auth.uid(): the subquery form lets the planner
-- hoist the call out of the per-row loop.
create policy "users read their own proposals"
  on public.proposals for select to authenticated
  using ((select auth.uid()) = user_id);

create policy "users insert their own proposals"
  on public.proposals for insert to authenticated
  with check ((select auth.uid()) = user_id);
